"""Constants for the Oilcam integration."""

DOMAIN = "ha_oilcam"

CONF_URL = "url"
CONF_PORT = "port"
CONF_UPDATE_CYCLE = "update_cycle"
CONF_ZIPCODE = "zipcode"
CONF_REGION = "region"
CONF_THRESHOLD_MIN = "threshold_min"
CONF_THRESHOLD_MAX = "threshold_max"
CONF_CAPACITY = "capacity"
CONF_HOST = "host"
CONF_LEVEL_LOW = "levelLow"
CONF_LEVEL_MEDIUM = "levelMedium"
CONF_COLOR_LOW = "colorLow"
CONF_COLOR_MEDIUM = "colorMedium"
CONF_COLOR_FULL = "colorFull"
CONF_COLOR_BOX = "colorBox"
